### ISSUE TITLE
Question: what is the benefit Integration with HTML::Pipeline?

### ISSUE THREAD

**Issue by qnoox** [jollygoodcode/twemoji#37]
Hello first of all thanks for an awesome gem!

so i had a question and was looking to learn more:
Question: what is the benefit to using the "Integration with HTML::Pipeline"?
Side Question: Do i have to use HTML::Pipeline?

Thank you in advance & keep up the awesome work!

**Comment by JuanitoFatas** [comment]
Hello,

Twemoji can be used without HTML::Pipeline. Most of the app we use twemoji is with markdown, and we typically implement markdown with HTML::Pipeline so that's why.

HTML::Pipelines not limited to markdown, it has many features to handle/customize your text, recommend you to use it.
