### ISSUE TITLE
Ruby 1.9.3 Support

### ISSUE THREAD

**Issue by bramswenson** [jollygoodcode/twemoji#4]
I'm sure you intentionally chose to exclude 1.9.3 since it is not going to be supported soon. I have a project that is going to be moving slowly to 2.x and have created a temporary fork/branch for 1.9.3 support here:
https://github.com/bramswenson/twemoji/tree/ruby-1.9.3

**Comment by JuanitoFatas** [comment]
Thanks Bram, [I mentioned your branch in the README.md](https://github.com/jollygoodcode/twemoji#ruby-193-support). Have a good day! :metal:
